//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ur5EMoveitConfig
{
    [Serializable]
    public class MoverServiceUr5eResponse : Message
    {
        public const string k_RosMessageName = "ur5_e_moveit_config/MoverServiceUr5e";
        public override string RosMessageName => k_RosMessageName;

        public Moveit.RobotTrajectoryMsg[] trajectories;

        public MoverServiceUr5eResponse()
        {
            this.trajectories = new Moveit.RobotTrajectoryMsg[0];
        }

        public MoverServiceUr5eResponse(Moveit.RobotTrajectoryMsg[] trajectories)
        {
            this.trajectories = trajectories;
        }

        public static MoverServiceUr5eResponse Deserialize(MessageDeserializer deserializer) => new MoverServiceUr5eResponse(deserializer);

        private MoverServiceUr5eResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectories, Moveit.RobotTrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
        }

        public override string ToString()
        {
            return "MoverServiceUr5eResponse: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
